#!/bin/bash

set -eu

path_root=$(dirname $0)/..
path_root=$(readlink -f ${path_root})

learn=${path_root}/learn
generate=${path_root}/generate

cd ${path_root}/test

for compress in 0 1; do
    if [ $compress -eq 0 ]; then
        compress_name="default"
    else
        compress_name="compress"
    fi
    echo "[test][simple][$compress_name] generating data..."
    rm -rf tmp
    mkdir tmp
    cd tmp
    echo "a b c d e f" > one.txt
    echo "d e f g i h" > two.txt
    echo "file:///$(pwd)/one.txt" > urls
    echo "file:///$(pwd)/two.txt" >> urls
    echo "[test][simple][$compress_name] learning model..."
    if [ $compress -eq 0 ]; then
        ${learn} -w 1 -i urls -c 4 -o model -v
    else
        ${learn} -w 1 -i urls -c 4 -o model --compress
    fi
    echo "[test][simple][$compress_name] generating sentence..."
    result=$(${generate} -i model -c 3 b c d e)
    if [[ "b c d e f g i h" == $result ]]; then
        echo "[test][simple][$compress_name] passed"
    else
        echo "[test][simple][$compress_name] failed"
    fi
done
